### PR TITLE
cleaner identity and upgrade material-ui

### PR DESCRIPTION
**Pull request by silviopaganini**
Let's embrace the new identity properly 

image

image

favicon-196x196

### CODE REVIEW

**Comment by grudelsud** [comment]
sorry I'm not really sold on this new domain. Can we please pause this and have a chat about it before changing logos and everything.

**Comment by silviopaganini** [comment]
regardless of the domain name or group name, there are some important changes in terms of design/structure here, we can merge this and revise naming later

**Comment by silviopaganini** [comment]
Also, note that we have a proper Privacy & Policy page now

**Comment by grudelsud** [comment]
shall we settle just for DevCon until we define a direction, as discussed f2f today? I've updated the copy for the time being, also put the bio in a tooltip. have a look and let me know if that's ok.

**Pull request merged**
